rush-02: dictionary.c ft_atoi.c ft_checking.c ft_strcpy.c rush-02.c decompose.c
	gcc -Wall -Werror -Wextra dictionary.c ft_atoi.c ft_checking.c ft_strcpy.c rush-02.c decompose.c free_dictionary.c -o rush-02

fclean:
	rm -f *.o rush-02
